import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const BASE = 'https://raw.githubusercontent.com/nagix/mini-tokyo-3d/master/data'

const round = (v, d) => Math.round(v * 10 ** d) / 10 ** d

async function get(name) {
  const res = await fetch(`${BASE}/${name}`)
  if (!res.ok) throw new Error(`${name} -> ${res.status}`)
  return res.json()
}

const railways = await get('railways.json')
const stations = await get('stations.json')

const nodeById = new Map()
for (const s of stations) {
  if (!s.coord || s.coord.length < 2) continue
  nodeById.set(s.id, { lat: s.coord[1], lng: s.coord[0], ja: s.title?.ja || '', en: s.title?.en || '' })
}

const lines = []
const lineIdx = new Map()
for (const r of railways) {
  const path_coords = []
  for (const sid of r.stations ?? []) {
    const n = nodeById.get(sid)
    if (n) path_coords.push([n.lat, n.lng])
  }
  const idx = lines.length
  lines.push({ id: r.id, en: r.title?.en || '', ja: r.title?.ja || '', color: r.color || '#888', path: path_coords })
  lineIdx.set(r.id, idx)
}

// istasyonları koordinat+ada gore tekilleştir, hatlarini birlestir
const stationGroups = new Map()
for (const s of stations) {
  if (!s.coord || s.coord.length < 2) continue
  const lat = s.coord[1]
  const lng = s.coord[0]
  const name = s.title?.en || s.title?.ja || ''
  if (!name) continue
  const key = `${round(lat, 3)},${round(lng, 3)}|${name}`
  const li = lineIdx.get(s.railway)
  if (li == null) continue
  const g = stationGroups.get(key) ?? { lat, lng, ja: s.title?.ja || '', en: s.title?.en || '', lines: new Set() }
  g.lines.add(li)
  stationGroups.set(key, g)
}

const outStations = [...stationGroups.values()].map((g) => ({
  lat: g.lat,
  lng: g.lng,
  ja: g.ja,
  en: g.en,
  lines: [...g.lines],
}))

const ts = `// Auto-generated by scripts/build-tokyo.mjs (from nagix/mini-tokyo-3d, ODPT-derived).
export interface LineDef { id: string; ja: string; en: string; color: string; path: [number, number][] }
export interface StationDef { lat: number; lng: number; ja: string; en: string; lines: number[] }
export const TOKYO_LINES: LineDef[] = ${JSON.stringify(lines)}
export const TOKYO_STATIONS: StationDef[] = ${JSON.stringify(outStations)}
`

const dest = path.join(__dirname, '..', 'src', 'data', 'tokyo.ts')
fs.mkdirSync(path.dirname(dest), { recursive: true })
fs.writeFileSync(dest, ts)
console.log(`wrote ${dest}: ${lines.length} lines, ${outStations.length} stations, ${(ts.length / 1024).toFixed(0)} KB`)
